### ISSUE TITLE
Please update JabRef

### ISSUE THREAD

**Issue by koppor** [OlafHaag/chocolatey-packages#6]
JabRef released a newer version and it seems that @Vaquero84 (or @thigg?) just has to regenerate `chocolateyInstall.ps1`.

**Comment by OlafHaag** [comment]
New versions are commited to the chocolatey package feed. Waiting for approval.

**Comment by koppor** [comment]
Yeah, 3.5 made it, but now, 3.6 has been released.  :innocent:

**Comment by koppor** [comment]
[JabRef 3.6 is available on chocolatey since August, 29](https://chocolatey.org/packages/JabRef#versionhistory) and awaiting moderation. Thank you for the quick update!

**Comment by OlafHaag** [comment]
The problem lies with the jre dependency and the recent chocolatey update to not allow for empty checksums. The JRE package wasn't yet updated to include checksums, so the installation of the jabref package on their validation system fails as well. The admins had been informed immediately and told me they are working on it with the maintainer, but nothing happened so far...

**Comment by koppor** [comment]
JabRef 3.7 was released. Is it OK to ask here for an update? 😇

**Comment by OlafHaag** [comment]
I'll try to update the package as soon as an issue with chocopackageupdater is resolved, which unfortunately doesn't work on my freshly setup system.

Am 14.11.2016 um 14:47 schrieb Oliver Kopp:

**Comment by koppor** [comment]
We released JabRef 3.8 today. Maybe this could convince the issue to go away :)

**Comment by OlafHaag** [comment]
The issue is with chocolatey. I was swamped as of late, but I'll get behind this this weekend. I may turn to the Google User Group for help as I want to be able to update packages again as soon as possible.
Thanks for letting me know!

Am 16.12.2016 um 23:10 schrieb Oliver Kopp:

**Comment by koppor** [comment]
Yeah, chocolatey package 3.8.1 was approved yesterday 🎉. We also released JabRef 3.8.2 yesterday. Is it possible to update it? 🤞

**Comment by OlafHaag** [comment]
My setup now looks every day for an update again.

**Comment by koppor** [comment]
The automatic update seems to fail for JabRef 5.0 (https://github.com/JabRef/jabref/releases/download/v5.0/JabRef-5.0.msi for Windows). Could you have a look please?

**Comment by OlafHaag** [comment]
Thanks for the report and sorry for the delay in response.
Actually, I thought @tobiasdiez was working on taking over maintainership for the chocolatey packages by incorporating them into the build process.

But I see, my AU script is failing with jabref for a while now.
I'll have a look. I also see there's a portable version, so I'll take the opportunity to create a package for it as well.

**Comment by OlafHaag** [comment]
At this point I could maybe even add the development snapshots as a stream. But this would require that the version number changes for each snapshot, since I only compare those to determine if there's a new version available.

**Comment by tobiasdiez** [comment]
My PR https://github.com/JabRef/jabref/pull/5378 concerns only the development version. I think it is easier to include the dev-stream as part of our deployment scripts (because it has access to the code to determine the exact version etc.). 

If you want we can also include the chocolatey packages for the stable releases in the JabRef repository. But as you did a awesome job maintaining them so far there is no real need for action!

**Comment by koppor** [comment]
He started working on it at https://github.com/JabRef/jabref/pull/5378. In our last JabRef devcall (https://github.com/JabRef/jabref/wiki/Minutes#2020-03-17-8oo --> SnapCraft dev build), we decided to

- keep JabRef stable chocolatey package as is (comparable to VLC https://chocolatey.org/packages/vlc)
- introduce a beta channel (not sure whether this is possible)
- introduce a nightly channel (comparable to VLC Nightly https://chocolatey.org/packages/vlc-nightly)

I volunteered to drive this as it seems "only" to be an issue with our GitHub actions (especially embedding https://github.com/marketplace/actions/chocolatey-action). I was just starting to understand what's going on and how the whole thing works.

@OlafHaag I would be happy if you kept maintaining the JabRef Chocolatey package - then the development team could focus on improving JabRef itself. 🎉

**Comment by OlafHaag** [comment]
Thanks for the update! Last night I went ahead and created new packages. Since I changed the setup to so-called virtual packages, I introduced 2 new packages (jabref.install & jabref.portable) which yet have to be approved by a chocolatey admin.

I also added a stream for the development snapshots, but that didn't quite work out the way I was expecting, because chocolatey only pushes the first updated stream and I couldn't manually push, because the stable packages weren't approved. So I'm glad you still have plans for that.

I'll let my script keep updating the stable releases.

If you want to have the descriptions changed for the packages, just let me know!

**Comment by koppor** [comment]
> Thanks for the update! Last night I went ahead and created new packages. Since I changed the setup to so-called virtual packages, I introduced 2 new packages (jabref.install & jabref.portable) which yet have to be approved by a chocolatey admin.

Seems they are approved:

- https://chocolatey.org/packages/jabref.install
- https://chocolatey.org/packages/jabref.portable

> I also added a stream for the development snapshots, but that didn't quite work out the way I was expecting, because chocolatey only pushes the first updated stream and I couldn't manually push, because the stable packages weren't approved. So I'm glad you still have plans for that.

OK, I will work on it and hopefully succeed. Currently, https://chocolatey.org/packages/JabRef shows "JabRef 5.1-dev". Can you change that back to "JabRef"?

> I'll let my script keep updating the stable releases.

Thank you!

**Comment by OlafHaag** [comment]
Unfortunately they are not approved yet. They both have the _READY_ status, so some moderator can appove them. They only passed the automatic validation and verification.
This manual process of approval seems quite slow, I assume it's due to a huge number of packages and a limited number of moderators.
There's also a textbox saying 

> This version is in moderation and has not yet been approved. 

The jabref package is a trusted package, meaning it bypasses manual approval (they must think I know what I'm doing). Since I changed it to a meta-package which only installs the jabref.install dependency that somehow works, even though the dependency isn't yet approved. From a security standpoint this should probably not be possible.

The website of the package only shows the latest version as a title, even if it's a pre-release, If you search for the package instead, it shows the latest stable version.

When I updated the dev-stream, the jabref 5,1-dev package went through, because it is trusted and a pre-release, but the jabref.install 5,1-dev and jabref.portable 5,1-dev packages were rejected and couldn't be pushed,  because there's no approved version of them yet.

I can't change the package version once it's pushed. I can only push the same version as long as it is not approved, reject the package, unlist it, or push another version.
 
So now I wait. I could then try to push the 2 dev packages again or unlist/reject the 5.1-dev package and not push the missing packages until you have your setup ready.
What will the naming of the dev version be like? In the choco docs there's something about how it sorts them and determines which version is the most recent.

**Comment by koppor** [comment]
Thank you for the long explanation!

> What will the naming of the dev version be like?

I will go for `jabref-nightly. (Similar to vlc --> https://chocolatey.org/packages/vlc-nightly).

**Comment by OlafHaag** [comment]
> I will go for `jabref-nightly. (Similar to vlc --> https://chocolatey.org/packages/vlc-nightly).

Aha, so you want to create a new package instead of pushing to the already existing packages?
I remember reading somewhere in the choco docs that it was encouraged to publich pre-release versions to the same package, only mark the version as pre-release, e.g. _jabref 5.1.0.20200402-nightly_, which in this case would only have a dependency on _jabref.install 5.1.0.20200402-nightly_.

But then, I guess, you can't choco install them side-by-side to still have the stable release around. Except for when one is the portable version...

**Comment by koppor** [comment]
@OlafHaag It seems, I understood something wrong. 😇 - Very good idea to have a pre-release version of the same package. Not sure what you mean by 

> At this point I could maybe even add the development snapshots as a stream. But this would require that the version number changes for each snapshot, since I only compare those to determine if there's a new version available.

(https://github.com/OlafHaag/chocolatey-packages/issues/6#issuecomment-602298689)

JabRef shows the updated version number in the about dialog (somewhere hidden since our switch to jpackage)


![grafik](https://user-images.githubusercontent.com/1366654/78291873-71ff8680-7526-11ea-88d9-ae63d8cb3ba0.png)

In our builds server (https://builds.jabref.org/master/), the time stamp changes, the filename does not. - Would it be possible to "just" create a new development snapshot each night? Maybe, it would be possibel to check for the timestamp on the server? Not sure? Maybe similar to `wget -nc`?

![grafik](https://user-images.githubusercontent.com/1366654/78291842-644a0100-7526-11ea-9143-624b9753a83f.png)

**Comment by OlafHaag** [comment]
If I make the date in the download links become part of the chocolatey package version for the nightly builds, then it should work.

If choco now allows [SemVer2.0.0](https://semver.org/spec/v2.0.0.html) then it could be _5.1-dev.20200331_, but the status of chocolatey/choco#1610 suggests otherwise. So it would have to be _5.1.0.20200331-dev_, for example.  
Chocolatey allows for [4 version segments](https://chocolatey.org/docs/create-packages#versioning-recommendations) and the fourth is reserved for fix-notation, which may be suitable for jabref nightly builds, since the old nightly builds don't seem to be available for download anymore, hence breaking those packages.

The only problem rigt now is that those packages are still not approved and as long as that's the case, I can't push new package versions. I'll contact some admin about that.

**Comment by koppor** [comment]
For pull requests, we create following SemVer:

    "FullSemVer":"5.1.0-PullRequest6232.201",

(Using GitVersion)

For the `master` branch [we produce](https://github.com/JabRef/jabref/runs/556129613):

    "FullSemVer":"5.1.0-ci.193",

The number `193` is distance in number of commits from the latest release. This should be OK, shouldn't it?

**Comment by OlafHaag** [comment]
This should be OK, if choco supports SemVer2.0.0. Otherwise the `193` must be moved to the fourth version segment.

**Comment by koppor** [comment]
We discussed again internally. What I understood: Chocolatey offers full releases and pre-releses. No third mode. Since JabRef offers full releases and *beta* releases (e.g., 5.0-beta), we would like to have the alpha and beta releases published as pre-release.

I would then focus again on https://github.com/JabRef/jabref/pull/5378 to offer jabref-nightly. Beging fully aware that parallel setup won't work (besides the user chooses the portable version for the one and the installed version for the other package).

Does that make sence?

**Comment by OlafHaag** [comment]
I think that makes sense. Users installing pre-releases are willingly taking the risk of using possibly unstable software. Even though a beta is probably more ready than a nightly build.

**Comment by OlafHaag** [comment]
At least the _jabref.install_ package is approved now, so once you become a maintainer of the packages on chocolatey.org you should be able to push the nightly builds. The _jabref.portable_ package is still awaiting approval. The admins told me the majority of reviewers do that in their spare time so it can take quite some time.

**Comment by koppor** [comment]
I think, the decision is that we are very happy that you @OlafHaag continues with updating the packages. With the dev versions, we had issues (because of deploying nightly builds). We currently don't have time to work on that (therefore, we closed https://github.com/JabRef/jabref/pull/5378).

As the most recent version of JabRef is available, I am closing this issue.

**Comment by koppor** [comment]
(CC of a message to chocolatey package community)

We (the JabRef team) noticed that the latest version is JabRef 5.8 and that there is a version 6.0 dev and version 5.9 is missing. 6.0 is no longer existing/not yet. We (the JabRef Team) originally planned 6.0 after 5.8 but needed to do a release meanwhile which is now 5.9
The latest dev version is now 5.10.

Addition:

Sorry for the inconvenience! We switched to 6.0-dev shortly after the release of 5.8, but decided to do 5.9-dev (which will be sort of maintenance release).

**Comment by Siedlerchr** [comment]
Hi, we just released Version 5.11 an the website still lists 6.0 pre release 
https://community.chocolatey.org/packages/JabRef#versionhistory

**Comment by OlafHaag** [comment]
Sorry it took so long for me to take a look. I don't actively use choco much anymore.
I used web-scraping before to find latest releases, so each time github would change their release page, it could break. I now switched to the Github REST API for the jabref repo's latest release which should be much more robust.

I also downgraded the dev-version, since it wasn't accepting "older" versions than 6.0.
New release packages are awaiting automatic validation/moderation.
